version: '3.8'

services:
  # Main API service (simulates LXC container)
  encoding-api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
      - "8001:8001"  # WebSocket port
    volumes:
      - ./api:/app:rw
      - ./test-data:/encrypted-storage:rw
      - /tmp/ram-processing:/tmp:tmpfs,size=4g,noexec,nosuid,nodev
    environment:
      - ENVIRONMENT=development
      - ENCRYPTION_MODE=dual
      - PARAMETER_VALIDATION=strict
      - REDIS_URL=redis://redis-queue:6379
      - DEBUG=true
      - LOG_LEVEL=debug
    depends_on:
      - redis-queue
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    user: "1000:1000"
    networks:
      - encoding-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis job queue
  redis-queue:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - encoding-net
    security_opt:
      - no-new-privileges:true

  # Test client tools container
  test-client:
    build: 
      context: ./client-tools
      dockerfile: Dockerfile.dev
    volumes:
      - ./client-tools:/app:rw
      - ./test-media:/test-input:ro
      - ./test-results:/test-output:rw
    environment:
      - API_BASE_URL=http://encoding-api:8000
      - ENCRYPTION_KEY_PATH=/app/test-keys
    depends_on:
      - encoding-api
    networks:
      - encoding-net
    profiles:
      - testing

  # Development proxy (simulates Proxmox networking)
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./templates/nginx/dev.conf:/etc/nginx/nginx.conf:ro
      - ./templates/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - encoding-api
    networks:
      - encoding-net
    profiles:
      - proxy

volumes:
  redis-data:
    driver: local

networks:
  encoding-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1